services:
  nest_app:
    build:
      context: .
      dockerfile: Dockerfile
    image: orion_server
    ports:
      - 3001:3001
    restart: always
    volumes:
      - .:/nest
      - /nest/node_modules
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_USERNAME: root
      DB_PASSWORD: root
      DB_DATABASE: orion

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: orion
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: